module.exports = {
  apps: [
    {
      name: "pad",
      cwd: "/var/www/influxwise-apps/apps/pad",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3001",
      env: { NODE_ENV: "production", PORT: "3001" },
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "400M",
    },
    {
      name: "flow",
      cwd: "/var/www/influxwise-apps/apps/flow",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3002",
      env: { NODE_ENV: "production", PORT: "3002" },
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "400M",
    },
    {
      name: "spark",
      cwd: "/var/www/influxwise-apps/apps/spark",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3003",
      env: { NODE_ENV: "production", PORT: "3003" },
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "400M",
    },
    {
      name: "revive",
      cwd: "/var/www/influxwise-apps/apps/revive",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3004",
      env: { NODE_ENV: "production", PORT: "3004" },
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "400M",
    },
    {
      name: "shield",
      cwd: "/var/www/influxwise-apps/apps/shield",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3005",
      env: { NODE_ENV: "production", PORT: "3005" },
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "400M",
    },
    {
      name: "admin",
      cwd: "/var/www/influxwise-apps/apps/admin",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3006",
      env: { NODE_ENV: "production", PORT: "3006" },
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "300M",
    },
  ],
};
